### ISSUE TITLE
Zip extraction fails when directory in zip comes alphabetically after the files inside it.

### ISSUE THREAD

**Issue by blendermf** [newman55/unity-mod-manager#10]
Because in the InstallMod method you create directories and files in the same loop, and the entries are all sorted alphabetically (and even if you weren’t using EntriesSortes it would still cause issues because the default is basically random order) sometimes the directory for the file you are extracting doesn’t exist yet and therefore the FileStream can’t be created to write the extracted file.

Either creating the directories in the loop before, or checking if the folder exists before creating the FileStream(and creating it if it doesn’t) would fix the issue.

**Comment by spacehamster** [comment]
Adding
* `Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(modsPath, entry.FileName)));` at line [222](https://github.com/spacehamster/unity-mod-manager/blob/master/UnityModManager/Mods.cs#L222)
* `Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(Environment.CurrentDirectory, entry.FileName)));` at line [133](https://github.com/newman55/unity-mod-manager/blob/master/Updater/Form.cs#L133)
would fix it. 
In what situation is a file sorted alphabetically before its containing directory?
