### ISSUE TITLE
GUIContent overloads for UIDraw functions

### ISSUE THREAD

**Issue by LoganDark** [newman55/unity-mod-manager#100]
I would like to add tooltips to my settings. :)

**Comment by newman55** [comment]
I added a tooltip. Does it suit you?
UI.RenderTooltip function and option to DrawAttribute.

**Comment by LoganDark** [comment]
Yes, that looks better, thank you! Hovering the label, instead of the control, makes the tooltip, as desired. I haven't tested it myself, but I think I consider this issue closed
