### ISSUE TITLE
PoP!_OS 22.04 LTS - Entering the command "mono UnityModManager.exe" results in Unhandled Exception error

### ISSUE THREAD

**Issue by KnightGabriel** [newman55/unity-mod-manager#109]
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I followed all the instructions properly and everything. Google couldn't help at all. I'm just trying to get mods for pathfinder kingmaker on linux.

**Comment by KnightGabriel** [comment]
@newman55 Please help me I've tried literally everything but there's nothing left to do and I can't find anyone else who's having the exact same issue on the same linux kernel.

**Comment by newman55** [comment]
I'm sorry for the delay. You can use the console version "mono console.exe"

**Comment by KnightGabriel** [comment]
Putting in that command in the path just gives me the option to either "delete" or "restore", nothing else

**Comment by newman55** [comment]
Select restore, then you can install

**Comment by KnightGabriel** [comment]
That just makes me install it again, after which it takes me back to the exact same "delete" or "restore" screen. I tried changing installation method but the only one available was "assembly" which was already selected.

**Comment by newman55** [comment]
Does it look like this?

![Screenshot 2023-02-26 102617](https://user-images.githubusercontent.com/36269897/221397843-5f64bd37-afda-4878-b18b-cf50141e44aa.png)

**Comment by KnightGabriel** [comment]
Yes it does, but there are no files listed under "Copying files to game", just the config.xml
[2:16 AM] =======================================
[2:16 AM] Applying patch to 'UnityEngine.UIModule.dll'...
[2:16 AM] Copying files to game...
[2:16 AM] Creating configs...
[2:16 AM]   Config.xml
[2:16 AM] Installation was successful.
[2:16 AM] Manager-0.25.4.0 is installed on [Pathfinder: Kingmaker] as [Assembly].
[2:16 AM] Enter key for command or press enter to exit.
[2:16 AM] D. Delete
[2:16 AM] R. Restore
[2:16 AM] Key:

**Comment by newman55** [comment]
Check this files in the \Kingmaker_Data\Managed\UnityModManager\ folder

**Comment by KnightGabriel** [comment]
The files seem to all be there in that folder

**Comment by newman55** [comment]
Then everything should work.

**Comment by KnightGabriel** [comment]
Then what do I do? Should I just install the mods and manually put them in the folder or something because it's not working with the terminal.

**Comment by newman55** [comment]
Yes you need to unpack mods into the mods folder

**Comment by KnightGabriel** [comment]
Did that and when I start the game they still won't show up in UMM menu. It's almost 3am for me I'm gonna continue trying tomorrow I need to go to sleep

**Comment by KnightGabriel** [comment]
Oh actually nevermind, just extracting them wasn't enough the actual mod files were located inside the extracted folders, I had to manually take them out and put them in the mod folder and now it's showing up on the UMM menu.

**Comment by newman55** [comment]
Right
