### ISSUE TITLE
Skater XL Beta (New Entrypoint)

### ISSUE THREAD

**Issue by nthansen** [newman55/unity-mod-manager#110]
Skater XL got a new beta update that breaks the existing entrypoint on titlescreen.start. Working again by updating the entrypoint to:
```xml
	<GameInfo Name="Skater XL Beta">
		<Folder>Skater XL</Folder>
		<ModsDirectory>Mods</ModsDirectory>
		<ModInfo>Info.json</ModInfo>
		<EntryPoint>[Assembly-CSharp.dll]MasterPrefabManager.Awake:After</EntryPoint>
		<MinimalManagerVersion>0.12.5</MinimalManagerVersion>
	</GameInfo>
```

Not sure if this is backwards compatible or if this change will stay once out of beta.

**Comment by nthansen** [comment]
For anyone trying to install Unity Mod Manager onto the Skater XL Beta, copy the code block I posted above and open the file 
`UnityModManagerConfigLocal.xml` located in the UMM folder.  Paste the code right after `-->` and before `</Config>`

**Comment by newman55** [comment]
Added

**Comment by nthansen** [comment]
Thank you!
