### ISSUE TITLE
How can i add UMM UI fonts on steam deck?

### ISSUE THREAD

**Issue by Xinkle** [newman55/unity-mod-manager#111]
I installed UMM to Steamdeck and it works properly.
But there are a few fonts on the UI font change screen (not all from Steamdeck desktop mode fonts). so it can't display non-English letters.
how can I add more fonts to UMM UI?

I already tried to put fonts on pfx/drive_c/windows/fonts folder but it didn't works

**Comment by newman55** [comment]
You are the first one who asks about it. I also don't know where the fonts are loaded from.
```
https://wiki.archlinux.org/title/fonts#Manual_installation
https://freefontsfamily.com/arial-font-family-free-download/
```

**Comment by Xinkle** [comment]
> You are the first one who asks about it. I also don't know where the fonts are loaded from.
> 
> ```
> https://wiki.archlinux.org/title/fonts#Manual_installation
> https://freefontsfamily.com/arial-font-family-free-download/
> ```

Thanks for reply. it seems UMM doesn't use fonts on archlinux. so i need to investigate it. 😢
