### ISSUE TITLE
[Config Hotfix] Skater XL Beta Entrypoint

### ISSUE THREAD

**Issue by nthansen** [newman55/unity-mod-manager#112]
Appreciate the quickness on the last config request! Looks like certain Skater XL beta mods aren't working properly as the entrypoint starts before some assets load in. Suggested change is to start the entrypoint at the title screen as solved by @DawgVinciSXL.

```xml
	<GameInfo Name="Skater XL Beta">
		<Folder>Skater XL</Folder>
		<ModsDirectory>Mods</ModsDirectory>
		<ModInfo>Info.json</ModInfo>
		<EntryPoint>[Assembly-CSharp.dll]TitleScreen.OnEnter:After</EntryPoint>
		<MinimalManagerVersion>0.12.5</MinimalManagerVersion>
	</GameInfo>
```

**Comment by newman55** [comment]
Changed for 0.25.5a
