### ISSUE TITLE
Pathfinder WOTR - UMM not appearring after latest update - GOG Version

### ISSUE THREAD

**Issue by LazyDunmer** [newman55/unity-mod-manager#114]
Hi, I was forced to do a clean install after data corruption and updated to the latest version of the game(2.1.3.J). Later after verifying files all seemed good so installed latest version of UMM(0.25.5.C). Upon launching game, the UMM UI doesn't appear as it usually should. I am honestly unsure if the error is mine or if the latest update has caused this. I have included the logs but do not have the skills to interpret them myself. I would be very grateful if you could shed some light on this.

[GameLog.txt](https://github.com/newman55/unity-mod-manager/files/11351425/GameLog.txt)
[Player.log](https://github.com/newman55/unity-mod-manager/files/11351448/Player.log)

**Comment by newman55** [comment]
Hi, the process does not reach UMM activation. The error occurs earlier.

**Comment by LazyDunmer** [comment]
Hi thanks for looking and for responding so quickly. Sorry, I am still unsure where to troubleshoot. Is this an installation issue with the base game or UMM for example? Or is it a case of there is too many possibilities to comb through?

**Comment by LazyDunmer** [comment]
The game is working fine. UMM isn't

**Comment by newman55** [comment]
Do you choose doorstop or assembly?

**Comment by LazyDunmer** [comment]
doorstop

**Comment by newman55** [comment]
UMM rarely conflicts with games. I don't see any other similar feedback, so you have a special case, but according to the logs I don't see a problem with which I could help. I can only advise you to download the game again.

**Comment by LazyDunmer** [comment]
ok thanks for your help

**Comment by LazyDunmer** [comment]
I'm closing this issue. A clean re-download and re-install fixed this issue when I paired with a slightly older version of UMM.
