### ISSUE TITLE
Content mods without assemblies

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#118]
@newman55 not sure how else to reach you. The mod community for Derail Valley is shifting to BepInEx and the rationale was that they heard UMM would be sunsetting. Could you please confirm if that's the case, because the user community much prefers UMM for sure.

**Comment by newman55** [comment]
Thanks for taking the time to share this. 

I release fixes, but growth may not be. Sorry for being so short. 
BepInEx is also a good option.

**Comment by mricher-git** [comment]
Thanks for sharing the update. Not looking for growth, it has all of the functionality we need. The only appealing tool on the BepInEx side for modders is possibly the Runtime Unity Editor, but user wise, the UMM GUI is a great tool for those who are less technically inclined. Many thanks for this create tool and all your hard work.

**Comment by mricher-git** [comment]
Hi newman55,

We are considering staying with UMM, one issue we have at the moment is a mod for Custom Skins on trains. The skins are produced by a number of people. Ideally the skins themselves would be a mod. The problem is UMM requires an AssemblyName by and an EntryMethod, so we can't use it for more generic items like **texture mods**. Any simple solutions come to mind? Perhaps a new entry in ModInfo that would negate the need for AssemblyInfo. The issue lies at: https://github.com/newman55/unity-mod-manager/blob/ad2ced9511f2211ef85070bd520582476ab1e07c/UnityModManager/ModManager.cs#L1166

**Comment by newman55** [comment]
Hi, I could work on that. It will take me a few days to investigate.

**Comment by mricher-git** [comment]
Great, thanks so much, will check back here for update.

**Comment by newman55** [comment]
Hi, I found something to hook on, but for now I'm halfway there. I just decided to report.

**Comment by mricher-git** [comment]
Thanks for the update. We have agreed to move back to UMM and are eagerly awaiting this feature before we officially announce it. Appreciate your support. You may want to change the title of this issue to "Add support for content mods" or similiar.

**Comment by mricher-git** [comment]
Not sure if you ever check you Nexus account, sent you a DM with details there. Cheers.

**Comment by mspielberg** [comment]
The core ask here is "ability to manage mods without assemblies." We intend to use this far beyond texture replacement, and we're not actually wanting UMM to add any behavior, more to remove some existing checks.

**Comment by newman55** [comment]
Added

**Comment by mricher-git** [comment]
Very much appreciated.
