### ISSUE TITLE
Make UnityModManager.dll available as NuGet package

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#119]
Would be nice to be able to reference UnityModManager.dll through a NuGet package, and it is a requirement for some larger mods out there to have all build dependencies satisfied so anyone can download and build the solution. Would you mind putting one up?

**Comment by newman55** [comment]
When we finish with the textures, if I remember, I'll see what can be done.

**Comment by newman55** [comment]
https://www.nuget.org/packages/UnityModManager/0.26.0

**Comment by mricher-git** [comment]
Already has 26 downloads. Thanks @newman55 for doing this so quickly. Cheers.
