### ISSUE TITLE
Load Derail Valley mods before the main menu

### ISSUE THREAD

**Issue by Insprill** [newman55/unity-mod-manager#120]
Some of my Derail Valley mods modify the main menu and therefore need to create their patches before it loads.
Can you change the starting point to `[Assembly-CSharp.dll]Bootstrap.SwitchToNextScene:Before`?
This will ensure mods get loaded just before the main menu does, but after VR is initialized.

**Comment by mricher-git** [comment]
I have tested removing StartEntry altogether, or setting it to the same as the current EntryPoint and it works fine. We'd appreciate if you could change it to allow mods to load earlier than they currently are.

**Comment by newman55** [comment]
starting point removed

**Comment by Insprill** [comment]
Thank you!
