### ISSUE TITLE
Is string type supported by IDrawable?

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#121]
I added a string to my ModSettings derived class but it's not displayed.

I see it's supported here as a fieldType:
https://github.com/newman55/unity-mod-manager/blob/5bc0ad45e16a9ad5e48a5b38390b9d5eb74c25e2/UnityModManager/UIDraw.cs#L119

But during the Draw method, it falls through here:
https://github.com/newman55/unity-mod-manager/blob/5bc0ad45e16a9ad5e48a5b38390b9d5eb74c25e2/UnityModManager/UIDraw.cs#L702

It passes the condition: (f.FieldType.IsClass && !f.FieldType.IsArray) and never makes it to the draw code.

**Comment by newman55** [comment]
It should be displayed as label. Is it wrong for you?

**Comment by newman55** [comment]
I'll check, maybe I didn't implement it.

**Comment by mricher-git** [comment]
Yes it does, I thought it would show up as a textfield
string Username = newman55

GUI:
Username [newman55         ]

**Comment by newman55** [comment]
Fixed

**Comment by newman55** [comment]
Need to set manager version to 0.27.1

**Comment by newman55** [comment]
I set expandWidth true by default for string and added textarea attribute.

Don't forget to set manager version to 0.27.2

**Comment by mricher-git** [comment]
Looks and working great! Many thanks.
