### ISSUE TITLE
Change StartingPoint for Derail Valley

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#122]
Apologies, seems we were a bit too quick to ask to remove StartingPoint. It used to load too late, now it's definitely loading too early. Would you please change startingpoint as follows:

<StartingPoint>[Assembly-CSharp.dll]DV.Globals.AssignSelfToHelpers:After</StartingPoint>

This function hooks BeforeSceneLoad and works perfectly.
A number of us have been running this for a few days to ensure it's correct before making the ask ;)

**Comment by newman55** [comment]
No problem
