### ISSUE TITLE
Enhancement: Keybinding without modifiers

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#123]
There are a lot of use cases where a modifier is not appropriate, like ASDW for walking and there are use cases whete we only need a modifier, such as "Sprint" or "Run" key.

Could we have a Draw.Keybinding attribute and a version of DrawKeybinding() that specifies whether modifiers should be displayed?

I'd roll my own but the EnabledKeys is private and I'd end up duplicating it.

Perhaps even make it only modifiers or only keycode. We can roll our own modifiers with a simple togglegroup so not as required.

**Comment by newman55** [comment]
I think it won't be a problem to disable modifiers for duplicate keys.

**Comment by dtandersen** [comment]
What if the binding included the keycode for both the primary key and modifier.

**Comment by newman55** [comment]
I have added auto-detection for assignments, which will allow to use modifiers as normal keys. I hope this is what was needed.

**Comment by mricher-git** [comment]
Was hoping for quite the opposite, I would like the user to be able to select a Keybind without any modifiers. I just wanted an option to hide the modiers so they could only select a single key. The new system would be ok if I can set a boolean to prevent modifiers, which is all I need.

**Comment by newman55** [comment]
They can select a key without modifiers, I don't forbid it.

**Comment by mricher-git** [comment]
So if I want to forbid modifiers, I guess I can strip it off during
OnChanged I suppose ya

**Comment by newman55** [comment]
Added DrawKeybindingSmart for newest display include disable key modifiers.
Added DrawType.KeyBindingNoMod which disable key modifiers for keybinding.

**Comment by dtandersen** [comment]
I see it's on nuget now, I'll give it a try.

**Comment by mricher-git** [comment]
That's awesome, thanks for the support.
