### ISSUE TITLE
Can't use Draw annotation with non-sequential Enum

### ISSUE THREAD

**Issue by fauxnik** [newman55/unity-mod-manager#125]
I think the reason this is happening is that the underlying code is using the enum value as an index rather than finding the index of the selected enum value. I can contribute a fix, but I may need some help to understand how to test it.

Relevant code is here: https://github.com/newman55/unity-mod-manager/blob/master/UnityModManager/UIDraw.cs#L1275

**Comment by fauxnik** [comment]
In the meantime, one workaround is to replace all `Draw` annotations with a custom draw method, and to use this helper method to render the enums.

```csharp
private static void RenderEnumOption<T>(string label, ref T value, ref bool expanded) where T : Enum
{
	GUILayout.BeginHorizontal();
	GUILayout.Label(label);
	GUILayout.Space(5);
	if (!expanded)
	{
		if (GUILayout.Button(value.ToString()))
		{
			expanded = true;
		}
	}
	else
	{
		foreach (T item in Enum.GetValues(typeof(T)))
		{
			string formatting = item.Equals(value) ? "<b>{0}</b>" : "{0}";
			if (GUILayout.Button(string.Format(formatting, item)))
			{
				value = item;
				expanded = false;
			}
		}
	}
	GUILayout.EndHorizontal();
}
```

**Comment by newman55** [comment]
Thanks, I also applied the fix to ToggleGroup.
I suppose we don't need RenderEnumOption?

**Comment by fauxnik** [comment]
> I suppose we don't need RenderEnumOption?

That's correct. We do not. That's simply the workaround that I've been using in the meantime, which I posted in case anyone else was encountering this, not knowing how long (or short, in this case) it'd be until an official fix could be merged and released.
