### ISSUE TITLE
Unable to change game path in the console interface

### ISSUE THREAD

**Issue by Pramuspl** [newman55/unity-mod-manager#132]
I'm trying to run console.exe on macOS, using mono. Unfortunately I provided an incorrect path to the game, denied access to it in the OS popup and now I'm unable to change it.

Whenever I run console.exe and select the desired game, I'm getting the access denied error and can't change the path. Where is it stored so I can remove it? Definitely not in the UMM folder as I redownloaded it and the problem persists.

**Comment by Pramuspl** [comment]
I downloaded the new version and it doesn't seem to solve the issue. Indeed, on the first run I got a mesage that the path is not readable and the program requested a change but when I provided a new path, the error popped up again, without even asking the OS for permission and subsequents reruns don't ask for changing the path any longer.

Thanks for the quick response though!

**Comment by Pramuspl** [comment]
Sorry to say that but it still doesn't seem to solve the issue.
![image](https://github.com/newman55/unity-mod-manager/assets/8478114/4d429609-a5ce-43e6-a0ea-4912463dabf3)
Trying to change the game and re-selecting it doesn't work either. Maybe it'd make sense to wipe the path and request it again when the user selects the game?

**Comment by newman55** [comment]
I've probably deleted something, try this [this](https://www.dropbox.com/scl/fi/bovut48iyjlt7vwwxe9l8/UnityModManagerInstallerDev.zip?rlkey=nzmbbdiiel0hgdpev1o1cqpfi&dl=1)

**Comment by Pramuspl** [comment]
> I've probably deleted something, try this [this](https://www.dropbox.com/scl/fi/bovut48iyjlt7vwwxe9l8/UnityModManagerInstallerDev.zip?rlkey=nzmbbdiiel0hgdpev1o1cqpfi&dl=1)

Nope, same thing. Error pops up and not re-asking for the new path.

**Comment by newman55** [comment]
I can only advise you to delete the file Params.xml . In windows, it is located in c:\Users\User\AppData\Local\UnityModManagerNet\
