### ISSUE TITLE
Planetbase 1.3.8 only works when UnityEngine.MonoBehaviour is patched

### ISSUE THREAD

**Issue by teor2345** [newman55/unity-mod-manager#134]
Currently UnityModManagerConfig.xml tries to patch UnityEngine.Canvas.cctor, but Planetbase 1.3.8 only works when UnityEngine.MonoBehaviour.cctor is patched.

**Comment by newman55** [comment]
Maybe this will work?
<EntryPoint>[UnityEngine.UIModule.dll]UnityEngine.Canvas.cctor:After</EntryPoint>

**Comment by teor2345** [comment]
> [UnityEngine.UIModule.dll]UnityEngine.Canvas.cctor:After

I also tried that and it didn't work! The game froze on launch instead.

**Comment by newman55** [comment]
Could you please show me the full line of what worked for you?

**Comment by teor2345** [comment]
My `Data/Managed/UnityModManager/Config.xml` contains:
`<EntryPoint>[UnityEngine.dll]UnityEngine.MonoBehaviour.cctor:Before</EntryPoint>`

I've attached the full file to this comment, I had to compress it because GitHub doesn't support XML files.

[Config.xml.zip](https://github.com/newman55/unity-mod-manager/files/14134446/Config.xml.zip)
