### ISSUE TITLE
Terra Invicta needs config update for DoorstopProxy installation method

### ISSUE THREAD

**Issue by JohnnyBoy91** [newman55/unity-mod-manager#135]
Hey I'm one of the Terra Invicta devs. We've had a large uptick in startup crashes from players who are using UMM with DoorstopProxy installation method.

It appears that one of our changes is causing UMM to fail on startup for reasons unknown to me, StartingPoint "StartMenuController.Start" seems to no longer work and crashes. We've add a new empty function which we won't modify and runs on start: "StartMenuController.EntryPoint" to be used as a safe starting point for UMM in future builds.

The change is present on the steam builds from 0.3.126 onwards.

**Comment by newman55** [comment]
Added. Thanks
