### ISSUE TITLE
Roadroader doesn't work with Doorstop 4.0.0rc-4

### ISSUE THREAD

**Issue by mricher-git** [newman55/unity-mod-manager#136]
I manually upgraded to latest doorstop 4.0.0 and it works fine. Could UMM update to latest doorstop 4.0.0 release?

**Comment by newman55** [comment]
Are you sure? Because nothing has changed for me.

**Comment by mricher-git** [comment]
Just tried a fresh install. When using the included winhttp 4.0.0rc-4, I get:
========== OUTPUTTING STACK TRACE ==================

0x00007FF9B8BA567C (KERNELBASE) RaiseException
0x00007FF91A010C0C (mono-2.0-bdwgc) mono_dl_fallback_unregister
0x00007FF919FFC822 (mono-2.0-bdwgc) BrotliEncoderVersion
0x00007FF919FFC8FC (mono-2.0-bdwgc) BrotliEncoderVersion
0x00007FF91A155AB1 (mono-2.0-bdwgc) mono_debug_init
0x00000001800037C6 (WINHTTP) WinHttpWriteProxySettings

I replace winhttp.dll with latest from doorstop github (4.0.0) and it works fine.

Assembly did work for me btw.

**Comment by newman55** [comment]
This is apparently another error. I'll add an update.

**Comment by newman55** [comment]
Fixed
