### ISSUE TITLE
Assembly does not work in Derail Valley for Arch Linux

### ISSUE THREAD

**Issue by DarthNader26** [newman55/unity-mod-manager#140]
I believe this might be related to #139. Whenever I try to install UMM through mono it dumps a ton of File Not Found errors in Derail Valley's console and can't load up the mod manager in game. The game's menus cannot be interacted with, but the music plays as normal. Uninstalling UMM and restoring the files returns the game's functionality.

I am on Manjaro Linux, using version 12b of the mod manager and build 98 of Derail Valley.

I'm happy to provide any logs or further information. I'm just not sure what would be helpful.

**Comment by newman55** [comment]
Maybe you downloaded the broken version before I re-uploaded it

**Comment by DarthNader26** [comment]
I redownloaded the installer last night to double check before posting this and I got the same result.

I have also tried running UMM through Proton and using the Doorstop method to see if that made a difference. I can interact with the menus in game, but I get weird behavior (I can't interact with my inventory until I open the inventory window i.e. hotkeys don't work) and I still get a bunch of NullReferenceExceptions pointing to the mod manager.

**Comment by newman55** [comment]
Try replacing `\DerailValley\DerailValley_Data\Managed\UnityModManager\0Harmony.dll` [to](https://github.com/pardeike/Harmony/releases/download/v2.3.1.1/Harmony-Fat.2.3.1.1.zip) from folder net472
and logs for me please

**Comment by DarthNader26** [comment]
That didn't seem to affect it. Unity Mod Manager does not seem to be generating any logs, unless I'm in the wrong place. Are there other logs that would be helpful?

![image](https://github.com/newman55/unity-mod-manager/assets/4230226/2dfb73ed-b723-4566-9932-0264246b2034)

**Comment by newman55** [comment]
Does version 0.27.10 work?

**Comment by DarthNader26** [comment]
I'll check when I get another chance.

I did find something interesting poking around. I tried installing through Proton and using Doorstop. When I checked doorstop_config.ini and tried to cd to the file path there, it threw an error. There are backslashes in the file path, which I think is correct for windows but wrong for Linux  (at least Manjaro?). Correcting those backslashes to forward slashes got rid of the NullReferenceException errors. I still wasn't getting the mod manager menu in game (and I don't think the mods I installed were working), but it did clear up the errors.

**Comment by DarthNader26** [comment]
> Does version 0.27.10 work?

Where can I find this version? I don't see 0.27.10 anywhere. The most recent two versions on Nexus are 0.27.12b and 0.27.7.

**Comment by newman55** [comment]
Get any

**Comment by DarthNader26** [comment]
I tried the previous available version and it also did not work.

**Comment by newman55** [comment]
So the reason is something else unique to you, I haven’t received any more feedback like this.
I would like to go back to the assembly again and get more error logs. In Windows, logs are stored in c:\Users\User\AppData\LocalLow\Altfuture\Derail Valley\; in Linux, you need to look for a similar storage.

**Comment by DarthNader26** [comment]
Got it. 

[Player.log](https://github.com/newman55/unity-mod-manager/files/14730511/Player.log)

**Comment by newman55** [comment]
1. Try replacing \DerailValley\DerailValley_Data\Managed\UnityModManager\0Harmony.dll [this](https://github.com/pardeike/Harmony/releases/download/v2.3.1.1/Harmony-Fat.2.3.1.1.zip) from folder net472

2. Try older version of UMM

and logs

**Comment by DarthNader26** [comment]
[Harmony Replacement.log](https://github.com/newman55/unity-mod-manager/files/14730545/Harmony.Replacement.log)

[Older Version.log](https://github.com/newman55/unity-mod-manager/files/14730549/Older.Version.log)

**Comment by newman55** [comment]
In all cases the same error. I don't even have any idea why this is happening. Are you launching the UMM via proton?

**Comment by DarthNader26** [comment]
I have tried launching through proton and launching through mono. Nothing seems to effect getting the error. I have also talked to other people using Arch on the Derail Valley server and they don't seem to have this problem. I'm not sure what could be wrong with my exact system that would be causing this. The game itself runs fine without the mod manager. I'd just really like to be able to mod it now that I've beaten it several times.

**Comment by newman55** [comment]
What if you move all the files from the \DerailValley\DerailValley_Data\Managed\UnityModManager\ folder to the Managed? 
Then don't forget to return them back.

**Comment by DarthNader26** [comment]
That worked! If they are in the Managed folder it seems to come up just fine. All the mods are working and everything seems to be functioning correctly.

**Comment by newman55** [comment]
I have made changes in the new version try it.

**Comment by DarthNader26** [comment]
Marking as closed. Thanks for your help!
