### ISSUE TITLE
Change EndsWith to Equals for Info.json file.

### ISSUE THREAD

**Issue by WhistleWiz** [newman55/unity-mod-manager#141]
This line has been causing issues when extracting mods automatically if there is a another file that ends with `info.json` (in the case we are running into, there is a `MapInfo.json` file with each map), and it gets found before the actual file UMM needs.

https://github.com/newman55/unity-mod-manager/blob/ed8c02d3df49d7641b16b7603a01c3cba511a9b6/UnityModManagerApp/Mods.cs#L424

[Here's a link to a zip with both files, but UMM finds the correct one first.](https://github.com/WhistleWiz/dv-mapify/releases/tag/Map-v0.1.0)

[And here is a link to a zip file that bugs.](https://github.com/WhistleWiz/dv-mapify/releases/tag/HSMap-v0.1.0)

There's the possibility of breaking existing mods with this change, but I believe a discussing could be had about it.

Json files that end "info" are rather common for mods, and it's very possible others have ran into this issue and not realised.

**Comment by newman55** [comment]
I'll improve the comparison, no problem.

**Comment by newman55** [comment]
Fixed

**Comment by WhistleWiz** [comment]
Thank you!
