### ISSUE TITLE
Defining load order?

### ISSUE THREAD

**Issue by WhistleWiz** [newman55/unity-mod-manager#143]
I have a question regarding mod load order and if there is a way to ensure a mod always happens before another one.

In my case (game is Derail Valley), I have 3 framework mods that all work fine together (Custom Licenses, Custom Cargo and Custom Car Loader).

Optionally, a cargo mod can require a license mod, and a car mod can require both a cargo and a license mod. In the case a user makes one mod specific for another one, is there a way to ensure the mods are loaded in a certain order, if they're all part of the same mod entry? So in this case, if a mod contains a license, a cargo and a car, is it possible to make sure the license part of the mod is loaded first?

**Comment by newman55** [comment]
To be honest, I didn’t understand the diagram, but all that is there for order is `Requirements: []` and `LoadAfter: []` in info.json. You can also find via `UnityModManager.FindMod(id)` and force activate it.

**Comment by WhistleWiz** [comment]
Yeah I did write it in a confusing way.

Let's say I have Mod 1, Mod 2 and Mod 3.

Mod 3 has json that Mod 1 reads, and a json that Mod 2 reads. I wanted to ensure Mod 1 always reads the jsons before Mod 2.

All of this happens on `UnityModManager.toggleModsListen`. If `LoadAfter` ensures that, it's all I need. It's missing on the github wiki BTW, so I had no idea it existed.

**Comment by newman55** [comment]
I didn't know there was a wiki here. The source is [here](https://wiki.nexusmods.com/index.php/How_to_create_mod_for_unity_game)

**Comment by newman55** [comment]
I think yes

**Comment by WhistleWiz** [comment]
Tried it out and it seems to work. I'll try a workaround if I get reports of it not working.
