### ISSUE TITLE
Feature Request: Add textbox to manually enter game path

### ISSUE THREAD

**Issue by Los2000** [newman55/unity-mod-manager#145]
Greetings:

Having some issues in Linux (Mint). When I first installed and executed the UnityModManager.exe file, using mono, it worked perfectly. It was able to locate my steam games without any issue (specifically Pathfinder WOTR). Unfortunately, one of the mods caused a game crash, and restoring the original game files caused UMM to go sideways. Now it cannot auto-locate the steam game folder, and more importantly, I cannot browse to it using the Browse For Folder popup (I presume the Linux equivalent of the Folder Browser in Windows). Unfortunately, this window does not allow hidden folders (those starting with "." such as ".steam") to be displayed. Apparently other versions of Linux will show hidden folders using "Ctrl-H" or "F8," but not Mint apparently.

Perhaps you can add a textbox option where the path to the folder can be typed in, instead of using the Folder Browser? BTW, where are these path settings saved? I poked around every file, and didn't find it.

**Comment by newman55** [comment]
The settings file is located in User\AppData\Local\UnityModManagerNet for windows.
You can enter the path manually in the console version.

**Comment by Los2000** [comment]
Thank you, the console did indeed work.  However I did find the UnityModManagerNet folder.  There was a single file "Params.xml."  It does not seem to reflect any changes made in either the console or the GUI.  (shrug...more Linux file strangeness).
