### ISSUE TITLE
Request to add: Big Ambitions

### ISSUE THREAD

**Issue by SmashingQuasar** [newman55/unity-mod-manager#150]
Hello,

Would it be possible to make UMM compatible with the game Big Ambitions, please? I am looking forward developing mods for this game. Unfortunately I am only familiar with Unreal Engine mods development, so I am unsure how to proceed to help with making UMM compatible with Big Ambitions.

I have no problem giving a hand if necessary, just let me know what you need!

**Comment by newman55** [comment]
Unfortunately, this is not possible with the UMM, the game is compiled in C++.

**Comment by SmashingQuasar** [comment]
Damn. Would you have any recommendations on how to decompile the game? I tried ILSpy but it did not manage to decompile the assembly files.

**Comment by newman55** [comment]
[bepinex](https://docs.bepinex.dev/master/articles/dev_guide/dev_tools.html)

**Comment by SmashingQuasar** [comment]
Thanks a lot! Closing this issue since it is not doable.
