### ISSUE TITLE
Need to test new update v 0.13

### ISSUE THREAD

**Issue by newman55** [newman55/unity-mod-manager#16]
The scheme of UnityModManagerConfig.xml has changed.
The UnityModManager class has been moved to the UnityModManager.dll file.
All libraries are moved to the UnityModManager folder.
Added 0Harmony with the traditional name.
Added calls associated with Update, LateUpdate, FixedUpdate.
Added a new way to install the manager used as in [Kingmaker Mod Loader](https://www.nexusmods.com/pathfinderkingmaker/mods/20). 
For Pathfinder: Kingmaker configured an alternative installation method.
For Pathfinder: Kingmaker has been changed the mods starting point to Kingmaker.GameStarter.StartGame: Before

90% of existing mods must be compatible. Others will need to be updated (recompiled).

[Link to download](https://www.dropbox.com/s/o72ehfmqia1pncp/UnityModManager.testbuild.zip?dl=1)

**Comment by RobRendell** [comment]
How do you want to measure the compatibility rating?  Do you want individual modders to chime in on this issue, reporting whether they've tested their own mods, and whether they're compatible?  Or do you want some sample of players or modders from each game that UMM supports reporting on compatibility of all mods they use?

For the record, my two Pathfinder: Kingmaker mods [Craft Magic Items](https://www.nexusmods.com/pathfinderkingmaker/mods/54) and [Faster Menu Book Zoom](https://www.nexusmods.com/pathfinderkingmaker/mods/67) appear to be compatible with the version currently available in the link.

**Comment by newman55** [comment]
@RobRendell 
Probably more interested in tests from different games. Because I do not have all the games and I do not want to release the update without making sure that it does not break their work.

**Comment by spacehamster** [comment]
Can you explain what the xml entries mean?
```
Could you explain the new xml fields 
<EntryPoint>[UnityEngine.UIModule.dll]UnityEngine.Canvas.cctor:Before</EntryPoint>
<StartingPoint>[Assembly-CSharp.dll]Kingmaker.GameStarter.StartGame:Before</StartingPoint>
<UIStartingPoint>[Assembly-CSharp.dll]Kingmaker.MainMenu.Start:After</UIStartingPoint>
<OldPatchTarget>[Assembly-CSharp.dll]Kingmaker.GameStarter.Awake:Before</OldPatchTarget>
```
When building, a command window pops up with the following message
```
Does C:\Code\unity-mod-manager\UnityModManagerApp\bin\Release\UnityModManager.exe specify a file name
or directory name on the target
(F = file, D = directory)?
```
On Mac, trying to install results in this error https://pastebin.com/mC855Kth
`<MachineConfig>MonoBleedingEdge\etc\mono\4.5\machine.config</MachineConfig>` needs to be changed to
`<MachineConfig>kingmaker.app/Contents/MonoBleedingEdge/etc/mono/4.5/machine.config</MachineConfig>` to install correctly

After installing on mac, launching the game gives this error https://pastebin.com/L3u1xyqK

On windows, I've found some mods to be incompatible with version 0.13, including Kingdom Resolution, Bag of Tricks and Toggle AI and Stealth Hotkey. The error they throw is 
```
[KingdomResolution] System.TypeLoadException: Could not load type UnityModManagerNet.UnityModManager+UI, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  ...snip...
  at Harmony12.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) [0x00007] in <455e5c1456634e14910c281b79c6c325>:0 
  at KingdomResolution.Main.Load (UnityModManagerNet.UnityModManager+ModEntry modEntry) [0x0003f] in <2f7eed5c815f4083947aa1e6638eebb5>:0 
```
which is caused by patching `UnityModManager.UI::Update`
```
[Harmony12.HarmonyPatch(typeof(UnityModManager.UI), "Update")]
internal static class UnityModManager_UI_Update_Patch
{
	private static void Postfix(UnityModManager.UI __instance, ref Rect ___mWindowRect, ref Vector2[] ___mScrollPosition, ref int ___tabId)
	{
		ummRect = ___mWindowRect;
		ummScrollPosition = ___mScrollPosition;
		ummTabId = ___tabId;
	}
}
```
In Kingdom Resolution, this was done in order to show tooltips, but Toggle AI and Stealth Hotkey does it to capture key events, and Bag of Tricks does it for both. The best solution for those types of incompatibility would probably be for the mods in question to be updated to 0.13

Do you know when the crypto rng entry point runs? In KML it was
 ```
KingmakerModLoader.StartUp..cctor() (at :0)
KingmakerModLoader.RngWrapper..cctor() (at :0)
...snip...
System.Guid.NewGuid() (at :0)
Kingmaker.GameStatistic..ctor() (at :0)
Kingmaker.Game..ctor() (at :0)
Kingmaker.Game..cctor() (at :0)
Kingmaker.Kingdom.KingdomState.get_Instance() (at :0)
Kingmaker.Kingdom.KingdomState.get_Founded() (at :0)
Kingmaker.Visual.Sound.SoundState.ResetState(Kingmaker.Visual.Sound.SoundStateType state) (at :0)
Kingmaker.UI.MainMenuUI.SplashScreenController+<DelayedShow>c__Iterator0.MoveNext() (at :0)
UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at :0)
```
Also, If the lack of control over the initialization time is an issue with the crypto rng entry point, there is an alternative [Unity Doorstop](https://github.com/NeighTools/UnityDoorstop) which runs before any unity code.

**Comment by newman55** [comment]
@spacehamster 

EntryPoint - a point in assembly for injection.
StartingPoint - loading mods.
UIStartingPoint - launch UI.
OldPatchTarget - is the PatchTarget from the previous version. Only needed to remove the old version.

I added a mechanism that recompiles assemblies by replacing the UnityModManager namespace with a new namespace that is in UnityModManager.dll.
But Harmony does not find them.

RNG starts late. I did not find a way to initialize it early.
I will try to replace it with Unity Doorstop. Maybe it will be even better.

**Comment by 6d306e73746572** [comment]
Bag of Tricks (Pathfinder Kingmaker) and Toolbox (Garden Paws) required updating the references (the error spacehamster already pointed out). 
All the rest worked immediately without any errors.

**Comment by spacehamster** [comment]
@newman55 
I was able to get something like this to work on a test app. https://gist.github.com/spacehamster/2e5d76794f6e83f9c1d9f156c0a35544
I'm not sure if this is the best way of doing it though.

**Comment by newman55** [comment]
@spacehamster 
My mistake was that I used 32 bit version instead of 64. Now your script works. It looks like a good solution. Thanks.

**Comment by newman55** [comment]
Link updated.
RNG installation method replaced by Unity Doorstop.
I disabled it for Unix systems assuming that they need to be compiled specifically.

For Pathfinder: Kingmaker has been changed the mods starting point as was in 0.12

**Comment by Tyler-IN** [comment]
Just curious, why is starting "late" an issue? What do you need to hook so early that the game isn't even loaded?

**Comment by spacehamster** [comment]
I didn't realize Doorstop was windows only. Unless it is made cross platform, the rng wrapper is probably the better solution. In pathfinder kingmaker, UMM runs before the localization manager is initialized, while KML runs after, so mods that patched the localization manager needed to be updated to support KML. I was worried similar issues might happen with other games. 

Another mod loader, [BepInEx](https://github.com/BepInEx/BepInEx/wiki/Writing-preloader-patchers) allows mono.cecil in memory patches, which I think is only possible by hooking in before the assemblies are loaded.

**Comment by newman55** [comment]
For Pathfinder, the Doorstop is now synchronized with the injection. In addition, the injections are transferred to unity files, which should reduce the cases of removing injections after updates.
I think for UNIX OS it should not be a problem to use injections.

**Comment by newman55** [comment]
I updated it on the nexus.
Thank you all for participating.

**Comment by RobRendell** [comment]
When I run version 0.12.7, it doesn't detect that there's an update... is that because 0.12 won't automatically update to 0.13?

**Comment by newman55** [comment]
That's right. Downloader has changed a bit.

**Comment by denikson** [comment]
> I didn't realize Doorstop was windows only. Unless it is made cross platform, the rng wrapper is probably the better solution. 

Doorstop is indeed only for Windows, but people have managed to run their games on Linux/macOS with Doorstop via Wine. It's nice to see Doorstop being used, but it's still a niche solution initially made for BepInEx and aimed mainly at Windows/Wine.

While it is possible to create patcherless versions of Doorstop for Linux and macOS, in the end true cross-platform solution is still hardpatching the DLLs (for instance, frameworks like MonoMod, IPA and BepInEx all provide hardpatchers as the only true cross-platform solution). Even then hardpatching is powerless against games running on IL2CPP. 

Can't have a silver bullet here.

**Comment by newman55** [comment]
@denikson, thanks for your work. Doorstop was included in UMM and is already in use. To run scripts used delayed start via harmony. For unix systems is used another method.
