### ISSUE TITLE
Line numbers not showing up in debug logs.

### ISSUE THREAD

**Issue by spacehamster** [newman55/unity-mod-manager#19]
In older versions of unity mod manager, if you installed dnspy debugging mono runtime and built mods with portable debug pdb, line numbers would show up in stack traces. 

This feature has stopped working in recent versions ever since UMM started caching mod assemblies. Changing the line
 https://github.com/newman55/unity-mod-manager/blob/7d7abcbaed7fcb7e6bf9ec5086dc1c8c98af4a90/UnityModManager/ModManager.cs#L480
to `Assembly.LoadFile(assemblyPath);` causes line numbers to start showing up.

**Comment by newman55** [comment]
Need to attach a pdb file? If rename it as assembly, would that work?

**Comment by spacehamster** [comment]
Sorry for taking so long, the first time I tried renaming the pdb, it didn't work, so I thought the fix would be more involved, but when I tried again, apparently not.
