### ISSUE TITLE
RoR2: Set isModded boolean when mods are enabled?

### ISSUE THREAD

**Issue by emoose** [newman55/unity-mod-manager#21]
Since UMM is adding support for RoR2 would it be possible for it to set the RoR2Application.isModded bool when mods are enabled? IMO it'd probably be better if the loader did that rather than the mods themselves, but it's up to you really.
(AFAIK that bool will make it so that modded trials won't effect the leaderboards and things like that, seems the RoR2 devs left a message for modders asking for it to be enabled: https://i.imgur.com/K2BNNiB.png)

Also I made a quick mod to test out UMM and it works perfectly, thanks a lot for this! Posted on reddit about it here: https://old.reddit.com/r/riskofrain/comments/b9pdq8/unitymodloader_now_works_with_ror2/

**Comment by newman55** [comment]
@emoose 
I think it can be done.

**Comment by newman55** [comment]
Added script in version 0.16.1

**Comment by po456asd** [comment]
Hello @newman55 i don't think forcing IsModded is a good idea since some of mod is not a really mod but it a bug fix like this example
https://github.com/ToyDragon/ROR2ModEngineerLunarCoinFix
it just a bug fix there shouldn't have Ismodded enable.
i want you to reconsider about this because i want this to untouch that option and have a mod developer to set this setting to true in their mod if their mod is a mod not just a fix or something that not affect gameplay like change ui or something.

best regards

**Comment by newman55** [comment]
@po456asd 
I actually agree with you. Mods can also be visual. But cheaters are very difficult to get to play fair. But still no protection will not stop them, so I would also like to remove this script and let it be on the conscience of the mod creators.

**Comment by po456asd** [comment]
Thanks you.

**Comment by emoose** [comment]
Ah, well I only suggested it because people on reddit seemed to think some other mod loader that auto-set this (can't remember which one) had it as an advantage over UMM, but now it seems the other main mod loaders in use (SeikoML/BepInEx) don't actually set it by themselves neither, so I guess it doesn't matter to people much.

Really it'd be my preference for the loader to set it, but with an option for mods to opt-out of needing that flag to be set (eg. a bool in the ModEntry struct), for mods like the bugfix/visual ones you'd mentioned. That way mod devs need less code to make 'proper' mods, and any skiddie cheaters would have to learn about that opt-out switch in order to not get their cheats flagged... maybe I'm overthinking it all though :P

**Comment by newman55** [comment]
Add the Cheating property to the config, which must be set to false to disable. Will it be a compromise?

**Comment by emoose** [comment]
Sounds good to me, so it'd be true by default and need the mod to explicitly set to false to disable? That'd be perfect.

I do kinda worry that some mod dev might make lots of changes but then set it to false because their mod isn't technically for cheating though, but that probably is just me overthinking things again...

Maybe make a note about that property in the README/docs, and mention that it should only be changed if the mod is for something minor?

**Comment by po456asd** [comment]
i don't think always set to true will work since they can just reinstall.
 keep disable and enable when mod config to modded is already looking good.

**Comment by emoose** [comment]
Oh I mean just in the session, not saved somewhere or anything like that, the way I meant is just to make sure loading other mods can't reset isModded back to false after you've already loaded a mod that set it.

eg. mod1 has Cheating = true, mod2 has Cheating = false, if you load mod1 first and then mod2 it might reset isModded to false even though a mod was loaded with Cheating = true, the way I meant was just to make sure once a Cheating mod has been loaded no other mod could un-set it, maybe you already have something like that though, not sure.

Anyway looking forward to trying it, thanks again!

**Comment by newman55** [comment]
What to do if the mod is already enabled during the session? IsModded will not affect anything.

**Comment by newman55** [comment]
I made the changes as we discussed and disabled the feature to disable the mods.
The Cheating field should be set to false in the info file.
The test build is available here https://www.dropbox.com/s/o72ehfmqia1pncp/UnityModManager.testbuild.zip?dl=1

**Comment by newman55** [comment]
I renamed Cheating to IsCheat and disabled it in the config. You can disable it correctly using the modEntry.Info.IsCheat = false.
