### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by andreamatt** [newman55/unity-mod-manager#23]
When a mod update is available, right click and update gives this error.
Adding this simple line
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
before creating a WebClient fixes the issue.

**Comment by newman55** [comment]
Added. 
Check the [build](url https://www.dropbox.com/s/o72ehfmqia1pncp/UnityModManager.testbuild.zip?dl=1)
Thanks.

**Comment by andreamatt** [comment]
Thanks to you, it fixed the issue for me.
