### ISSUE TITLE
Unable to use runtime reloading - "The version is exactly the same as the previous one"

### ISSUE THREAD

**Issue by jorgenpt** [newman55/unity-mod-manager#24]
I'm trying to use runtime reloading to be able to quickly iterate on my mod without having to restart the game. I'm using UMM 0.17.0 and I put `"ManagerVersion" : "0.17.0.0"` in my Info.json to get support for runtime reloading. My main class has the `[EnableReloading]` attribute on it, and when I load I see that `modEntry.CanReload` is true.

When I get in-game, clicking the Reload button does nothing. The log says `Reload is not needed. The version is exactly the same as the previous one.` This happens even if I change the  `[assembly: AssemblyVersion("1.0.0.0")]` in my AssemblyInfo.cs between builds, and it comes from here:
https://github.com/newman55/unity-mod-manager/blob/master/UnityModManager/ModManager.cs#L605

First, I'm not sure why this check is here -- if it's a debug / testing option, wouldn't it be OK to just let me reload my assembly without having to modify my assembly version every time? Second, I'm not sure why this is failing -- it seems like it should find the version to be different in my case, since I'm manually modifying the assembly version & rebuilding before hitting "Reload".

I am testing this on Garden Paws. Any ideas on what could be going on?

**Comment by jorgenpt** [comment]
@newman55, unrelated -- how do you debug UMM in-game with MSVS? When I attach the debugger to the running instance, I don't seem to be able to set any breakpoints ("no symbols loaded") for any of my code, nor any of the code in UMM.

**Comment by newman55** [comment]
Hi @jorgenpt
Debugging process is possible only via [dnspy](https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games), and then not all versions of unity.

As for overloading assemblies, the CLR caches assemblies and will not allow you to load the same version. Make sure your DLL in the mod folder has really changed the version after the update.

**Comment by jorgenpt** [comment]
@newman55 I changed `AssemblyVersion`, and I verified in properties in explorer that the details of the assembly showed the new file version.

**Comment by jorgenpt** [comment]
I will see if I can make any sense of it with dnSpy the next time I poke around. Thank you for the pointer!

**Comment by d-simple** [comment]
Can't get reloading to work too and get same "Reloading isn't needed" message. 
I produced two dlls with differing versions and made a test snippet:
```
static void Main(string[] args)
        {
            string aPath;

            aPath = @"C:\test.dll";
            var asbl = Assembly.Load(File.ReadAllBytes(aPath));
            Version v1 = asbl.GetName().Version;
            Console.WriteLine(v1);

            aPath = @"C:\testOld.dll";
            asbl = Assembly.ReflectionOnlyLoad(File.ReadAllBytes(aPath));
            Version v2 = asbl.GetName().Version;
            Console.WriteLine(v2);

            if (v1 == v2)
            //Error!
                Console.WriteLine("What the actual");
        }
```
This obviously works fine, i.e. versions are different.

**Comment by newman55** [comment]
In different versions of unity, it works differently. I also saw games in which assembly loading is hard cached.
