### ISSUE TITLE
UMM UI is dark, and doesn't lock base game UI

### ISSUE THREAD

**Issue by spacehamster** [newman55/unity-mod-manager#29]
For Pillars of Eternity II: Deadfire, the UI is really dark, and when clicking on things, the main game's UI also reacts.

![image](https://user-images.githubusercontent.com/3821056/66716313-04e12300-ee18-11e9-9a3f-a7c71344b3ba.png)

**Comment by newman55** [comment]
Perhaps in the game ui is rendered by the meshrenderer component, in this case I have no idea how to block it. Do you know which ui the game uses?

**Comment by spacehamster** [comment]
It looks to be a heavily customized version of NGUI, UI is made up of almost entirely monobehaviors that are responsible for rendering the UI.

**Comment by spacehamster** [comment]
It looks like there is a UICamera monobehaviour attached to a UnityEngine.Camera responsible for processing and dispatching input events. I think i could probably block the UI by patching/modifying that.

**Comment by newman55** [comment]
Use UnityModManager.UI.Instance.Opened if you need to check the status. 
If it works, you can add a script [here](https://github.com/newman55/unity-mod-manager/blob/master/UnityModManager/Games.cs).

**Comment by spacehamster** [comment]
I'll give it a go, do you have any ideas why UMM's UI is so dark?

**Comment by newman55** [comment]
I will try to add a lighter texture.

**Comment by spacehamster** [comment]
It seems to be an interaction with UMM and the game, UMM looks fine in other games.
![image](https://user-images.githubusercontent.com/3821056/66747889-61ecdf80-eed1-11e9-8e7e-00371c250ccb.png)

**Comment by newman55** [comment]
I added a new option FixBlackUI to config that uses a lighter texture.

**Comment by spacehamster** [comment]
![image](https://user-images.githubusercontent.com/3821056/66753256-1ccfaa00-eedf-11e9-9889-8a4f9b32926f.png)
Its definitely an improvement, but i'm still unsure about what caused it to look different in the first place.

**Comment by newman55** [comment]
Just in case, I made it lighter if suddenly in some other games it will be even darker. I think now it looks good so that our eyes do not hurt.
In addition, the buttons in each version seem to have a different texture.

**Comment by spacehamster** [comment]
So I figured out what was with the UI, it seems it is due to gamma correction. If the textures are created with sRGB sampling disabled, the UI looks normal. Fixing it is just a matter of changing this line https://github.com/newman55/unity-mod-manager/blob/9d3393b96981b74575dd08ee5e04cbe73499b3a1/UnityModManager/Textures.cs#L40 to 
```csharp
 f.SetValue(null, new Texture2D(2, 2, TextureFormat.ARGB32, false, true));
```
Doing that means that the light mode is no longer needed. I also found a way to lock the UI, I see two ways of doing it, which is more preferable?
Method 1
```
class NewGame : GameScript
{
	//Add new override
	public override void OnToggleWindow()
	{
		LockGameUI(UnityModManager.UI.Instance.Opened);
	}
}
```
Method 2
```
class NewGame : GameScript
{
	public override void OnBeforeLoadMods()
	{
		var uiLocker = new GameObject().AddComponent <UILocker>();
		UnityEngine.Object.DontDestroyOnLoad(uiLocker);
	}
	class UILocker : MonoBehaviour
	{
		bool uiOpened;
		void Update()
		{
			if(UI.Instance.Opened != uiOpened)
			{
				uiOpened = UI.Instance.Opened;
				LockGameUI(UI.Instance.Opened);
			}
		}
	}
}
```

**Comment by newman55** [comment]
1. Apparently it depends on which mode the render works, I somehow forgot about it. Good job.
2. The first method seems to me more compatible, can be useful for other mods.
