### ISSUE TITLE
System.ComponentModel.TypeDescriptor static class constructor does not run.

### ISSUE THREAD

**Issue by TYoung86** [newman55/unity-mod-manager#3]
I don't know how UMM does this, but for Pathfinder: Kingmaker, it causes System.ComponentModel.TypeDescriptor._internalSyncObject to never be set. It's set first-thing in the System.ComponentModel.TypeDescriptor static initializer.

This causes calls to Newtonsoft.Json.Deserialize to begin failing.

Here it's null and throwing NullReferenceException;
![_internalSyncObject is null](https://user-images.githubusercontent.com/6979049/46908964-daa11080-cef8-11e8-9dc5-c4be351ca8c2.png)

This is how it *should* be initialized;
![_internalSyncObject static initializer](https://user-images.githubusercontent.com/6979049/46908970-fd332980-cef8-11e8-8bca-1fdde3fe503a.png)

The type has the beforefieldinit flag on it, so the static class constructor should always run before contained methods are executed;
![beforefieldinit](https://user-images.githubusercontent.com/6979049/46908985-38355d00-cef9-11e8-8013-5beffeb92321.png)

**Comment by TYoung86** [comment]
My workaround currently begins with this;
```csharp
      // compatibility with UMM
      var fi = ReflectionHelper.GetStaticFieldInfo<System.ComponentModel.TypeDescriptor>("_internalSyncObject");
      var getter = ReflectionHelper.GetStaticFieldGetter<object>(fi);
      var setter = ReflectionHelper.GetStaticFieldSetter<object>(fi);
      if (getter() == null) setter(new object());
      // end compatibility with UMM
```

**Comment by TYoung86** [comment]
KingmakerModLoader is designed to be minimally invasive and forward compatible with patches, updates, other mods, etc.

It currently patches no game dlls on disk and while bundling Harmony it doesn't even use it at present. 

https://gitlab.com/tyler-in/kingmaker-mod-loader

**Comment by newman55** [comment]
Thank you for the tips a lot of useful information. But I think it's gonna be hard to change something without breaking compatibility.

**Comment by Tyler-IN** [comment]
The issue comes down to the class beforefieldinit attribute.

http://csharpindepth.com/Articles/General/Beforefieldinit.aspx

All you have to do is inject the call to Start at a different/later time.

**Comment by newman55** [comment]
Hi Tyler, I want to try to add your KML's loading mechanism to UMM. You do not mind?

**Comment by Tyler-IN** [comment]
Go for it man. Take anything you want.

**Comment by spacehamster** [comment]
Some things to note with the KML loading mechanism, it probably needs extra work to be compatible with mac (see [here](https://github.com/newman55/unity-mod-manager/issues/7#issuecomment-452276961)), and it has a different entry point then currently specified, so any mods that depend on the current entry point (e.g. that certain objects are or aren't initialized) may need updating to work.
