### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by Hi-ImKyle** [newman55/unity-mod-manager#36]
So I've been modding unity games for a while now but there's always this one thing that pops up more than others that is a real pain and you seem to have "fixed" it with UMM but looking at the code I can't quite figure out what is different. So maybe you can help me out.

I've been trying to use `GUILayout` in all of my unity modding projects but it never seems to show up on screen.

`MainWindow = GUI.Window(0, MainWindow, MainWindowFunc, "Main");` [Result](https://i.imgur.com/o7K3gCI.png)

`MainWindow = GUILayout.Window(0, MainWindow, MainWindowFunc, "Main");` [Result](https://i.imgur.com/Gm6mnCP.png)

Am I missing something? As UMM uses `GUILayout` just fine, even in the same game! I've tried Googling this issue countless times and nothing shows. Maybe you have an idea?

**Comment by newman55** [comment]
The first parameter is the window ID and umm already uses 0. You need to request a free ID from the UnityModManager.UI.GetNextWindowId() or choose any other one. 
`
var id = UnityModManager.UI.GetNextWindowId();
MainWindow = GUILayout.Window(id, MainWindow, MainWindowFunc, "Main");
`

**Comment by Hi-ImKyle** [comment]
I understand how the window system works. I was more meaning without UMM. The code with images is ran without UMM, and in fact I can say it still happens exactly the same with UMM installed. 

Regardless of what ID I use, `GUILayout` does not show a window and in fact causes `OnGUI` to not even be called. Whereas `GUI` works just fine.

**Comment by newman55** [comment]
There is nothing special. Maybe you need to set sizes?

**Comment by Hi-ImKyle** [comment]
Tried, the main window rect is the same size and position as the one that's being used for the `GUI.Window` call which shows a window just fine as you see in the result image.

**Comment by Hi-ImKyle** [comment]
Tried new things, unfortunately for me it's a silly fix. Setting the windows `MinWidth` and `MinHeight` via the options when calling the window I can get the window to show, which if you ask me isn't how it should work and I know it's not how it works as ive used `GUILayout` without this silly fix perfectly fine before. It should just draw without adding a minimum width or height. This is the same for the controls themselves, they need to have their minimum width and height set or else they wont show up and will cause issues.

Closing because Unity sucks and so does their IMGUI.
