### ISSUE TITLE
Adding pre-built versions to github releases?

### ISSUE THREAD

**Issue by Chtobi** [newman55/unity-mod-manager#37]
Unfortunately, Nexus mods doesn't allow to download mods without registration, also it cuts down your downloading speed unless you buy a premium.

It would be better to upload new versions also to github releases or to the moddb.com.

**Comment by newman55** [comment]
[Dropbox](https://www.dropbox.com/s/wz8x8e4onjdfdbm/UnityModManager.zip?dl=1)

**Comment by Chtobi** [comment]
> 
> 
> [Dropbox](https://www.dropbox.com/s/wz8x8e4onjdfdbm/UnityModManager.zip?dl=1)

Thank you.
May be it's still better to use github releases or at least to add this dropbox link to the readme.md ?

**Comment by newman55** [comment]
The link is published on nexus.

**Comment by Chtobi** [comment]
> 
> 
> The link is published on nexus.

Sorry, didn't check the mirrows section. Thanks again.
