### ISSUE TITLE
Cannot run without .NET 3.5

### ISSUE THREAD

**Issue by OriginNRG** [newman55/unity-mod-manager#4]
I cannot install .NET 3.5 no matter what I do. Even tried a clean install of Windows. Is it possible to have this running with more recent versions of .NET? I currently have 4.7 installed. Not sure if its something that can be implemented.

**Comment by DoctorVanGogh** [comment]
# Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8

https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

---

I believe the current reliance of the "installer" running on 3.5 is predicated on 3.5 being the "lowest common denominator" for Unity applications. 
Unity can offer either 3.5 or 4.7.? .NET (mono) runtimes in-game. 

So the installer and ingame components are written against the same runtime for (presumably) convenience.

**Comment by newman55** [comment]
@DoctorVanGogh 
Yes, it is, most games works on .NET Framework 3.5

@OriginNRG 
Windows has many bugs. Similarly, other users may experience the problem of installing .NET Framework 4. Try downloading 3.5 from another source.
