### ISSUE TITLE
EntryMethod not called if game started with mod disabled

### ISSUE THREAD

**Issue by RobRendell** [newman55/unity-mod-manager#42]
Hi!  My mod needs to perform "downgrade" operations on player saves when it is disabled, so I still require an entry point even if it is disabled.  However, it appears that (with my current configuration at least), the configured EntryMethod is not invoked if the mod is disabled (toggled off in the "on/off" column in the in-game UMM UI) at the time the game starts up (i.e. it was toggled off in the previous session, the game exited, and then the game is restarted).

I assume this is by design, and it makes a lot of sense for UMM to behave like this - for a lot of mods, the author probably doesn't actually check `modEntry.Active` to ensure their mod should do its thing in their entry point, so not calling the entry point at all provides a good mechanism to disable the mod.

However, in my case I still want to run some code when the mod is still installed but disabled.  Is there any configuration that can be set in `info.json` to define an "inactive entry point"?  Or to tell UMM that my entry point does respect `modEntry.Active`, so I'd like it to be called even if the mod is disabled?

(I don't imagine it makes a difference to this behaviour, but for what it's worth this is for Owlcat's Pathfinder: Kingmaker game)

Thanks!

**Comment by newman55** [comment]
Hi.

This is done in order to allow players to disable a conflicting mod without causing errors in a game. If you load assembly anyway, it can cause crashes in the worst case.

In your case, I think it's better to add the Activated/Disabled button to the mod itself, and handle the behavior of saves regardless of the UMM functionality.

**Comment by RobRendell** [comment]
Fair enough.  Thanks!
