### ISSUE TITLE
Upgrade to Harmony 2.0

### ISSUE THREAD

**Issue by spacehamster** [newman55/unity-mod-manager#44]
Harmony 1.2 and Harmony 2.0 are not compatible, so to upgrade, i believe the best way forward would be to replace 0Harmony-1.2.dll and 0Harmony12.dll with a new library that forwards hamony calls to use harmony 2.0, so that way only harmony 2.0 patches are used and compatability with mods that harmony 1.2 is maintained.

I have started writing a library to do that [here](https://github.com/spacehamster/HarmonyProxy), but currently unity mod manager has two libraries with different namespaces (0Harmony-1.2.dll - Harmony, 0Harmony12.dll - Harmony 12), and the proxy does not currently support that. I am curious why UMM does have two harmony libraries btw.

**Comment by newman55** [comment]
Hi.

I have not seen new versions yet.

The second library contains a different namespace, so it will not cause conflicts for example with harmony 20.

**Comment by newman55** [comment]
I tested today what I wrote about and it turned out that I was wrong. Different namespaces do not make them compatible. Harmony and Harmony12 will even conflict when they patch the same method. It was a big mistake to add two libraries.

**Comment by spacehamster** [comment]
I've created a branch to test out harmony 2 with unity mod manager using harmony proxy [here](https://github.com/spacehamster/unity-mod-manager/tree/harmony2). Harmony Proxy should allow mods that use harmony 1.2 and mods that use harmony 2.0 to run along side each other and maintain compatibility, and it seems to work ok, but I think it needs more testing to ensure it doesn't break anything.

**Comment by newman55** [comment]
I released a new version with your update. I have tested a little with my mods and it seems to work perfectly. You came up with a great idea to make a proxy, it will be useful for many projects.

You helped me again. I owe you one.

**Comment by spacehamster** [comment]
Harmony has just released a 2.0.1 version, and I think it will make for a better base then Harmony 2.0.0.10 which was included in the previous version, i've updated the fork [here](https://github.com/spacehamster/unity-mod-manager/tree/harmony2)

**Comment by newman55** [comment]
Did this.

Harmony is the original file, or you compiled it?

**Comment by spacehamster** [comment]
I didn't compile it, I pulled it from nuget. It is the .NET 3.5 release library.

**Comment by spacehamster** [comment]
I've fixed some minor bugs that caused mods that tried to list out all the patches to return empty lists. https://github.com/spacehamster/HarmonyProxy
Did you want me to do a PR?

**Comment by newman55** [comment]
I downloaded it.
