### ISSUE TITLE
UMM does not get injected if Assembly-CSharp is not version 0.0.0.0

### ISSUE THREAD

**Issue by Modiseus** [newman55/unity-mod-manager#51]
The game that I am trying to mod has set the assembly version property of `Assembly-CSharp` to `9.0.0.0` which causes UMM to not get injected into the game.

The problem lies in this piece of code
https://github.com/newman55/unity-mod-manager/blob/014fc9e4e27ffc2bf0bd28b1abe15703c2e3eee1/UnityModManager/ModManager.cs#L956

I would suggest changing this to `args.LoadedAssembly.GetName() == "Assembly-CSharp"` witch does not depend on the Version (unless there is a reason that the full name has to match).

**Comment by newman55** [comment]
Fixed
