### ISSUE TITLE
Multiple different setting items with same values affects the first one

### ISSUE THREAD

**Issue by WallyCZ** [newman55/unity-mod-manager#53]
Consider this Settings class:
```csharp
public class Settings : UnityModManager.ModSettings, IDrawable
{
    [Draw(DrawType.KeyBinding)] public KeyBinding BindingToA = new KeyBinding() { keyCode = KeyCode.A };
    [Draw(DrawType.KeyBinding)] public KeyBinding BindingToB = new KeyBinding() { keyCode = KeyCode.B };
    [Draw(DrawType.KeyBinding)] public KeyBinding BindingToC = new KeyBinding() { keyCode = KeyCode.C };
}
```

Current behaviour is when you change BindingToB or BindingToC, it always set only BindingToA

Problem is in this code, which compare PopupToggleGroup_GUI based only on values they have. Of course key bindigs have always same set of items (keys):

https://github.com/newman55/unity-mod-manager/blob/f1798d7a32cbddf28e72d409b7692193db6ddcce/UnityModManager/ToggleGroup.cs#L196

**Comment by newman55** [comment]
Accepted. Thanks.
