### ISSUE TITLE
It's impossible to get the version if it requires several method calls

### ISSUE THREAD

**Issue by benediktwerner** [newman55/unity-mod-manager#59]
To get the version in Desperados III you need to call something like `MiVersion.Version.ToFullString()` where `Version` is a getter. As far as I can tell the parser always sees `MiVersion.Version` as a type and tries to call the `ToFullString` method on it but since `MiVersion.Version` is not actually I type it fails.

I would be up to implement a fix but I wanted to ask first what you think the best solution is. My two ideas would be to either check every combination if one of them is a getter or introduce some special syntax to separate the type from the calls, like maybe `MiVersion::Version.ToFullString` similar to how you get a method in Java. Although the `:` would clash with the `:After` so maybe something else would be better, maybe `$` or `@`. On the other hand, since for the version the `:After` modifiers don't make sense anyways it could be used anyways and be separate from the code that parses the actual entry points. And of course, the old method still has to work in any case.

Besides that, quick question while I'm at it: The guide for adding a new game says that the starting point should be as early as possible. Is there a reason to have it really early (like even before the main menu) besides maybe that mods could then modify very early code?

And another thing, maybe it would be a good idea to close issues after they are solved? Otherwise, it gets a bit hard to see the ones that are actually still open.

**Comment by newman55** [comment]
1. The version is interpreted as a static method or static field. So you can just write it in the config like this. 
<GameVersionPoint>[Assembly-CSharp.dll]MiVersion.Version.ToFullString</GameVersionPoint>
Other ways can be implemented through additional processing [script](https://github.com/newman55/unity-mod-manager/blob/8be8e021853dd21159d033993a1665c2d1ee72db/UnityModManager/Games.cs#L103).

2. There is no reason. I wrote this for those who do not understand what they need. You can choose any position.

3. I think some of the answers will warn against duplicating topics. In addition, you can close the issues yourself.

**Comment by benediktwerner** [comment]
> The version is interpreted as a static method or static field. So you can just write it in the config like this.
[Assembly-CSharp.dll]MiVersion.Version.ToFullString

Yeah, I get that and tried that already but `MiVersion.Version` is a getter so what I need to do is more like `MiVersion.get_Version().ToFullString()`. I don't think that's currently possible, right? I can see that it would be possible if the last call was `ToString` since that is called automatically but that doesn't return a proper version string for this game.

GameScripts seem like a possible solution. Do I understand that correctly that I should just create a PR that adds a game script to the file you linked? If that's the preferred way then I'll do that.

I was just wondering if it wouldn't be better to implement a more general solution that wouldn't require a game script for every game where you can't get the version with a direct static field access or method call. But I guess that's maybe not that common so game scripts might be the easiest solution. It's your call, I would be happy to implement a solution that works for the XML config but I also don't mind just creating a game script.

2. Ok, thanks for the info.

3. That's true, though I don't think that really applies to issues asking to add a game. I would close them myself if I could but only you or the person that created the issue can close it. But I guess it doesn't really matter, I just wanted to point it out.

**Comment by newman55** [comment]
You're right, two methods cannot be used at once. But now I have no other solution.
Your script will look something like this.
```csharp
class DesperadosIII : GameScript
{
    public override void OnBeforeLoadMods()
    {
        string ver = "Get value via reflection";
        gameVersion = ParseVersion(ver);
    }
}
```

**Comment by benediktwerner** [comment]
> But now I have no other solution.

Yes, I know, that's exactly why I'm offering to implement a solution 😅

I'm not sure if I'm somehow not communicating my point properly.

Basically, I think the best solution would be if there were a way to do this without GameScripts. I'm totally fine with writing a GameScript but I think it would be better overall if this would be possible without a GameScript since it would make it easier for other (future) games that might have the same problem and not require a special GameScript for each of them.

After thinking about it a bit, I think it would be best if you could do this: `<GameVersionPoint>[Assembly-CSharp.dll]MiVersion.get_Version().ToFullString()</GameVersionPoint>`. The old way could still work but UMM could for example detect if the string contains `()` and then parse it the new way.

If you think this sounds like a good idea then I would implement this in UMM. If you have a better idea for how this could work I would also be happy to implement that. I'm also fine if you think this sounds like a stupid idea in which case I'm totally okay with just writing a GameScript.

I just want to have a clear answer on what you prefer. So far it feels like you have been kind of avoiding my question and just pointing at the game scripts without saying anything about whether or not you would accept those changes and I'm not really sure what to make of that. If you don't want me to do any changes, that's totally fine with me but please just tell me.

**Comment by newman55** [comment]
If this does not break compatibility, I'm all for it.

**Comment by benediktwerner** [comment]
Ok, thanks, here is the PR: #60
