### ISSUE TITLE
Horizontal attribute doesn't work

### ISSUE THREAD

**Issue by benediktwerner** [newman55/unity-mod-manager#61]
Since the attribute is [only usable for classes and structs](https://github.com/newman55/unity-mod-manager/blob/master/UnityModManager/UIDraw.cs#L106), I would expect the usage to be like this:

```c#
[Horizontal]
public class CustomThing { ... }

public class Settings : ModSettings, IDrawable {
        [Draw] public CustomThing whatever = new CustomThing();
}
```

However, [in the draw code](https://github.com/newman55/unity-mod-manager/blob/master/UnityModManager/UIDraw.cs#L586), the presence of the attribute is checked on the member and not its type, requiring usage like this:

```c#
public class Settings : ModSettings, IDrawable {
        [Draw, Horizontal] public CustomThing whatever = new CustomThing();
}
```

This is obviously not possible, since the attribute can not be put on a member.

The possible fixes I see are to allow putting the attribute on members, check the attribute on the field type, or both.

**Comment by benediktwerner** [comment]
I now created PR #62 to fix this the way that seems most sensible to me, but feel free to give your opinion.

**Comment by newman55** [comment]
Thanks
