### ISSUE TITLE
Mod manager crashes on open if there's already an instance open

### ISSUE THREAD

**Issue by PhilPJL** [newman55/unity-mod-manager#70]
Ideally the app should detect the running instance, bring it info focus and exit gracefully.

**Comment by PhilPJL** [comment]
I have a fix for this but waiting to see what you do with https://github.com/newman55/unity-mod-manager/pull/75

**Comment by newman55** [comment]
Fixed

**Comment by PhilPJL** [comment]
Ok, you did it differently from me, but if it works that's great.
This is my solution: https://github.com/PhilPJL/unity-mod-manager/blob/master/UnityModManagerApp/Program.cs
I have no idea if it would work across platforms.

**Comment by PhilPJL** [comment]
MainForm.Activate() worked for me, so I didn't need to use
`        [DllImport("user32.dll", SetLastError = true)]
        private static extern bool SetForegroundWindow(IntPtr hwnd);`

**Comment by newman55** [comment]
Understood

**Comment by PhilPJL** [comment]
Internally Activate calls SetForegroundWindow

    public void Activate()
    {
      IntSecurity.ModifyFocus.Demand();
      if (!this.Visible || !this.IsHandleCreated)
        return;
      if (this.IsMdiChild)
        this.MdiParentInternal.MdiClient.SendMessage(546, this.Handle, 0);
      else
        UnsafeNativeMethods.SetForegroundWindow(new HandleRef((object) this, this.Handle));
    }
