### ISSUE TITLE
Not an Issue: Request for Update

### ISSUE THREAD

**Issue by ThyWoof** [newman55/unity-mod-manager#72]
Please change Solasta entrypoint on any upcoming release. We need to get earlier in the game before it binds user settings. Entrypoint should be acticalAdventuresApplication.Start. This:

<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="Solasta">
  <Folder>Solasta</Folder>
  <ModsDirectory>Mods</ModsDirectory>
  <ModInfo>Info.json</ModInfo>
  <GameExe>Solasta.exe</GameExe>
  <EntryPoint>[UnityEngine.UIModule.dll]UnityEngine.Canvas.cctor:Before</EntryPoint>
  <StartingPoint>[Assembly-CSharp.dll]TacticalAdventuresApplication.Start:After</StartingPoint>
  <MinimalManagerVersion>0.22.13</MinimalManagerVersion>
</Config>

**Comment by newman55** [comment]
What will happen to the existing mods, have you checked their compatibility?

**Comment by ThyWoof** [comment]
Yep... Discussed it already with @spacehamster. Shouldn't cause any issue as we have been asking modders to use `[HarmonyPatch(typeof(MainMenuScreen), "RuntimeLoaded")]` if they need access to any internal blueprint.

**Comment by newman55** [comment]
Thanks. Added.
