### ISSUE TITLE
Dependencies not available in \lib

### ISSUE THREAD

**Issue by PhilPJL** [newman55/unity-mod-manager#73]
UnityModManager.csproj references ..\..\lib\UnityEngine.dll and ..\lib\UnityEngine.UI.dll.
Please add these dlls to the lib folder.
You also don't document which version of Unity you are targetting.

**Comment by newman55** [comment]
The links are located inside the lib folder.

**Comment by PhilPJL** [comment]
I don't see them and the project doesn't build because they're missing

![image](https://user-images.githubusercontent.com/271656/113412144-7071d400-93af-11eb-8406-fb529e5f9a8f.png)

![image](https://user-images.githubusercontent.com/271656/113412066-3b658180-93af-11eb-9cd9-9d66cfd7ae06.png)

**Comment by newman55** [comment]
They are located in the libraries file, I'm sorry if I didn't make myself clear.

**Comment by PhilPJL** [comment]
'libraries' is a file when the repo is cloned

![image](https://user-images.githubusercontent.com/271656/113413184-ed9e4880-93b1-11eb-800a-c4351cbbc6f5.png)

and it doesn't contain the dlls required

![image](https://user-images.githubusercontent.com/271656/113413232-0eff3480-93b2-11eb-90d8-e9c7eeb0a937.png)

and even if it did the project file references dlls in the lib folder, not lib\libraries

**Comment by newman55** [comment]
It contains download links. I don't think I can put part of the Unity project here.

**Comment by PhilPJL** [comment]
That's another good reason for using Nuget packages - you don't need to include binaries in your repo.  Unfortunately there isn't an official Nuget package for Unity.

**Comment by PhilPJL** [comment]
If you can put those files on dropbox for download I don't see why you can't add them to the lib folder.

**Comment by PhilPJL** [comment]
Ok closing but l think you should add the unity libs
