### ISSUE TITLE
HarmonyX nuget package

### ISSUE THREAD

**Issue by PhilPJL** [newman55/unity-mod-manager#74]
Would it be sensible to replace the 0Harmony.dll dependency with the HarmonyX nuget package ref?

**Comment by newman55** [comment]
Do you need it? I very poorly understand how it differs from the original.

**Comment by PhilPJL** [comment]
If you reference a nuget package you will
1) also pull in any dependencies that package has
2) easily discover updates
3) easily switch to specific versions

Ignore the additional Unity references here - I had to pull in lots of stuff to get it to build due to the missing Unity dlls.
![image](https://user-images.githubusercontent.com/271656/113412524-68666400-93b0-11eb-8b6f-bddacf30d75a.png)

Also projects that depend on the UnityModManager project will get transitive dependencies automatically.
So UnityModManagerApp doesn't need to reference 0Harmony.dll because it already references UnityModManager.

Same goes for other stuff like NewtonSoft and Ionic.Zip

You would also then notice that Ionic Zip is no longer maintained and maybe choose something else.
![image](https://user-images.githubusercontent.com/271656/113412665-c3985680-93b0-11eb-83d3-bde8e99971f8.png)

Maybe UnityModManager should itself be published as a Nuget package.

**Comment by PhilPJL** [comment]
Of course this isn't going to work if you need to continue supporting .NET 3.5.  Is there a reason for not moving to .NET 4.7 say?

**Comment by PhilPJL** [comment]
I've created a version of the app using Nuget packages where possible and updated to .NET 4.8.
https://github.com/PhilPJL/unity-mod-manager.
It works but obviously leaves behind .NET 3.5.

**Comment by newman55** [comment]
UMM is already compiled on 4.5 and the reason for supporting 3.5 is because 4.5 doesn't work for everyone.

**Comment by PhilPJL** [comment]
Ok closing.
