### ISSUE TITLE
Unable to Install Working Mods on UMM 0.23.3

### ISSUE THREAD

**Issue by MCBTay** [newman55/unity-mod-manager#78]
I've written quite a few mods for SkaterXL.  Yesterday, they released an update to the game so I started updating my mods too.  While I was at it, I was unable to actually install any of my zip files using UMM 0.23.3.  The only way I was able to get them to install was to either install them manually, or to downgrade to UMM 0.22.15c.

Is this expected?

![image](https://user-images.githubusercontent.com/1085747/114276762-1b107500-99f6-11eb-997b-b0011be1828d.png)

Of course this file doesn't exist yet, as I'm trying to install the mod.  Please let me know if there's anything else I can provide you to help debug this.

**Comment by newman55** [comment]
Can I see the zip file?

**Comment by MCBTay** [comment]
Absolutely. These zips are created as a part of my post build steps, so not much room for user error as far as creating them.

[XLMenuMod-2-3-0.zip](https://github.com/newman55/unity-mod-manager/files/6290564/XLMenuMod-2-3-0.zip)

**Comment by newman55** [comment]
I found the error. I'll update it tomorrow. Thanks.

**Comment by MCBTay** [comment]
Awesome, thank you so much!

**Comment by MCBTay** [comment]
0.23.4 seems to have resolved the issue, so going to close this bug.
