### ISSUE TITLE
Updating mod doesn't remove old dependencies

### ISSUE THREAD

**Issue by PhilPJL** [newman55/unity-mod-manager#81]
[SolastaUnofficialHotFixes_1_0_6.zip](https://github.com/newman55/unity-mod-manager/files/6650808/SolastaUnofficialHotFixes_1_0_6.zip)
[SolastaUnofficialHotFixes_1_0_7.zip](https://github.com/newman55/unity-mod-manager/files/6650809/SolastaUnofficialHotFixes_1_0_7.zip)

For example if I load V1.0.6 which has a dependency on System.Text.Json the mod folder will contain

![image](https://user-images.githubusercontent.com/271656/121949729-b7395e00-cd50-11eb-9354-e2752dbf8af2.png)

If I now update to V1.0.7 where I changed to have a dependency on NewtonSoft.Json doesn't need deploying the folder should look like this:

![image](https://user-images.githubusercontent.com/271656/121949848-dcc66780-cd50-11eb-956d-7e7e6fc7a500.png)

But the old System.Text.Json dependencies are still there.  
Suggest cleaning folder when updating a mod.

**Comment by newman55** [comment]
That's right, updates don't delete anything. This is done in order not to delete the generated resources or configs. In your case, this file will not harm anyone.

**Comment by PhilPJL** [comment]
ok
