### ISSUE TITLE
Make UMM downloadable via gh release

### ISSUE THREAD

**Issue by developomp** [newman55/unity-mod-manager#87]
This should be better than having to create a nexusmods account.

**Comment by newman55** [comment]
You can download it from the mirror

**Comment by developomp** [comment]
They can't be trusted

**Comment by newman55** [comment]
Why?

**Comment by developomp** [comment]
It's not from the UMM creator

**Comment by newman55** [comment]
The link that is listed on the nexus is from me.

**Comment by developomp** [comment]
Might wanna put that on readme

**Comment by newman55** [comment]
Done
