### ISSUE TITLE
Mod manager UI is transparent to mouse clicks

### ISSUE THREAD

**Issue by PhilPJL** [newman55/unity-mod-manager#89]
Using mod manager 0.23.4/0.24.0 with Solasta.
If the mod manager UI is opened in game any mouse click or drag is passed through to the game UI.  This is unwanted and annoying behaviour.
If `BlockGameUI` is supposed to prevent this, it's currently not working.  Maybe a Unity version compatibility issue?

**Comment by newman55** [comment]
I am not familiar with Solasta, maybe it has a custom UI. BlockGameUI overlaps the native UI.

**Comment by PhilPJL** [comment]
Ok, confirmed that UMM works as expected on at least one other game (Pathfinder KM).
Solasta is doing something funky to grab the mouse.  We'll implement a specific solution for Solasta unless you have any ideas.
