### ISSUE TITLE
UMM fails to determine architecture of Xbox store UWP protected apps

### ISSUE THREAD

**Issue by akintos** [newman55/unity-mod-manager#90]
due to UWP encrypting exe binary files, UMM fails to determine arch of it and fails to install.

https://github.com/newman55/unity-mod-manager/blob/6977146966390163c64f3bc6b4ffa7506b8367f4/UnityModManagerApp/Form.cs#L877

If `Utils.UnmanagedDllIs64Bit(gameExePath)` fails, it should retry using other unencrypted dlls such as `UnityPlayer.dll` or `WinPixEventRuntime.dll`

**Comment by newman55** [comment]
I made changes, try [this](https://www.dropbox.com/s/o72ehfmqia1pncp/UnityModManager.testbuild.zip?dl=0).

**Comment by akintos** [comment]
thank you, it is working well!

https://github.com/newman55/unity-mod-manager/blob/9233f7a03c6a27abe809710b4eed56ce708729c5/UnityModManagerApp/Form.cs#L355

btw, I guess this semicolon is a mistake?

**Comment by newman55** [comment]
Thanks, I'll fix.
