### ISSUE TITLE
Update Harmony

### ISSUE THREAD

**Issue by LoganDark** [newman55/unity-mod-manager#98]
I need `MethodType.Enumerator` but it was [only added around 9 months ago](https://github.com/pardeike/Harmony/commit/bdd168f755a1a9eaf18d8948463077c2f16116e1), whereas the version of Harmony currently shipped with UMM is over 2 years out of date. What should I do about this?

**Comment by newman55** [comment]
You need to add manager version to info file
`"ManagerVersion": "0.24.6"`

**Comment by LoganDark** [comment]
> You need to add manager version to info file `"ManagerVersion": "0.24.6"`

how is this relevant?

**Comment by newman55** [comment]
If you do not specify required version for a mod, it will cause an error when using the previous version manager.

**Comment by LoganDark** [comment]
> If you do not specify required version for a mod, it will cause an error when using the previous version manager.

does this have anything to do with updating the harmony version?

**Comment by newman55** [comment]
Forget
